// <auto-generated />
using System;
using CAFE_AI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CAFE_AI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260623143731_AddOrdersAndOrderItems")]
    partial class AddOrdersAndOrderItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CAFE_AI.Models.AIConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AiServiceUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxRecommendations")
                        .HasColumnType("int");

                    b.Property<double>("SentimentThreshold")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("AIConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AiServiceUrl = "http://127.0.0.1:8000",
                            MaxRecommendations = 5,
                            SentimentThreshold = 0.5
                        });
                });

            modelBuilder.Entity("CAFE_AI.Models.Drink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Drinks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Coffee",
                            Description = "Cà phê truyền thống Việt Nam",
                            ImageUrl = "https://images.unsplash.com/photo-1541167760496-1628856ab772?q=80&w=300",
                            IsAvailable = true,
                            Name = "Cà phê sữa đá",
                            Price = 29000m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Coffee",
                            Description = "Sữa tươi pha cà phê",
                            ImageUrl = "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=300",
                            IsAvailable = true,
                            Name = "Bạc xỉu",
                            Price = 32000m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Coffee",
                            Description = "Cà phê với trứng béo ngậy",
                            ImageUrl = "https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?q=80&w=300",
                            IsAvailable = true,
                            Name = "Cà phê trứng",
                            Price = 45000m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Tea",
                            Description = "Thanh mát giải nhiệt mùa hè",
                            ImageUrl = "https://images.unsplash.com/photo-1556679343-c7306c1976bc?q=80&w=300",
                            IsAvailable = true,
                            Name = "Trà đào cam sả",
                            Price = 39000m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Smoothie",
                            Description = "Sinh tố xoài tươi mát",
                            ImageUrl = "https://images.unsplash.com/photo-1553530666-ba11a7da3888?q=80&w=300",
                            IsAvailable = true,
                            Name = "Sinh tố xoài",
                            Price = 42000m
                        });
                });

            modelBuilder.Entity("CAFE_AI.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("DrinkId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<double>("SentimentConfidence")
                        .HasColumnType("float");

                    b.Property<string>("SentimentLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DrinkId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("CAFE_AI.Models.FeedbackReply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FeedbackId")
                        .HasColumnType("int");

                    b.Property<string>("ReplyText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("StaffId");

                    b.ToTable("FeedbackReplies");
                });

            modelBuilder.Entity("CAFE_AI.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CAFE_AI.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DrinkId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DrinkId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("CAFE_AI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "manager@cafe.com",
                            FullName = "Quản lý Cafe",
                            PasswordHash = "$2a$11$9/kP636/rS1iIqQk1Z4xueYd9G0fLwH5Bswp2iM.D4.yV5e3t.292",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "staff@cafe.com",
                            FullName = "Nhân viên Phục vụ",
                            PasswordHash = "$2a$11$9/kP636/rS1iIqQk1Z4xueYd9G0fLwH5Bswp2iM.D4.yV5e3t.292",
                            Role = "Staff"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "customer@cafe.com",
                            FullName = "Khách hàng VIP",
                            PasswordHash = "$2a$11$9/kP636/rS1iIqQk1Z4xueYd9G0fLwH5Bswp2iM.D4.yV5e3t.292",
                            Role = "Customer"
                        });
                });

            modelBuilder.Entity("CAFE_AI.Models.Feedback", b =>
                {
                    b.HasOne("CAFE_AI.Models.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CAFE_AI.Models.Drink", "Drink")
                        .WithMany()
                        .HasForeignKey("DrinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Drink");
                });

            modelBuilder.Entity("CAFE_AI.Models.FeedbackReply", b =>
                {
                    b.HasOne("CAFE_AI.Models.Feedback", "Feedback")
                        .WithMany("Replies")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CAFE_AI.Models.User", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Feedback");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("CAFE_AI.Models.Order", b =>
                {
                    b.HasOne("CAFE_AI.Models.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CAFE_AI.Models.OrderItem", b =>
                {
                    b.HasOne("CAFE_AI.Models.Drink", "Drink")
                        .WithMany()
                        .HasForeignKey("DrinkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CAFE_AI.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drink");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CAFE_AI.Models.Feedback", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("CAFE_AI.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
